
#  Numpy Funcation

In [3]:
import numpy as np

### arange()

In [23]:
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [5]:
odd = np.arange(1,13,2)
print(odd)

[ 1  3  5  7  9 11]


### linspace()

In [25]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

### reshape()

In [17]:
ar_2d = arr_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [27]:
ar_3d = arr_1d.reshape(2,3,2)
print(ar_3d)
print(np.reshape(ar_2d,(4,3),order='F'))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[ 1  3  5]
 [ 7  9 11]
 [ 2  4  6]
 [ 8 10 12]]


### ravel()

In [13]:
ar_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### flatten()

In [14]:
ar_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### transpose()

In [21]:
ar_2d.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [28]:
x=np.arange(12)  
y=np.reshape(x, (4, 3), order='F')  
x  
y  

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])