In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,3,7]])

In [3]:
myarr

array([[3, 6, 3, 7]])

In [4]:
myarr.shape
myarr.dtype


dtype('int32')

In [5]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [6]:
listarray.dtype

dtype('int32')

In [7]:
listarray.shape

(3, 3)

In [8]:
rng = np.arange(12)

In [9]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
lspace = np.linspace(1,5,12)

In [11]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [12]:
lspace2=np.linspace(1,100,5)

In [13]:
lspace2

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [14]:
emp = np.empty((4,5))


In [15]:
emp

array([[1.78020033e-306, 1.24611266e-306, 8.06637656e-308,
        8.90070286e-308, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000]])

In [16]:
emp_like=np.empty_like(lspace2)

In [17]:
emp_like


array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [18]:
ide = np.identity(10)

In [19]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
ar1=np.array([1,2,3,4,56,7,8])


In [21]:
ar1.size


7

In [22]:
ar1.argmax() #its return   index of max value

4

In [23]:
ar1.argmin() #its return index of min value

0

In [24]:
ar1.T

array([ 1,  2,  3,  4, 56,  7,  8])

In [25]:
ar1.argsort() #return sorted index of given array

array([0, 1, 2, 3, 5, 6, 4], dtype=int32)

In [26]:
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype=np.int8)

In [27]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [28]:
ar3=ar2.T

In [29]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [30]:
ar3.ndim

2

In [31]:
ar3.size

9

In [32]:
ar3.argmin()

0

In [33]:
ar3.argmax()

8

In [34]:
ar3.sum(axis=0)

array([ 6, 15, 24])

In [35]:
ar3.sum(axis=1)

array([12, 15, 18])

In [36]:
ar3.argmax(axis=0)

array([2, 2, 2], dtype=int32)

In [37]:
ar3.argmax(axis=1)

array([2, 2, 2], dtype=int32)

In [38]:
ar3.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [39]:
ar4= ar3.flat

In [40]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [41]:
for i in ar4:
    print(i)

1
4
7
2
5
8
3
6
9


In [42]:
ar3.nbytes

9

In [43]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [44]:
ar3.sum(axis=0)

array([ 6, 15, 24])

In [45]:
ar3.sum(axis=1)

array([12, 15, 18])

In [46]:
ar3.argmax(axis=0)

array([2, 2, 2], dtype=int32)

In [47]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [48]:
ar3.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int32)

In [49]:
ar3.dtype

dtype('int8')

In [50]:
ar3.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int32)

In [51]:
ar3.ravel()

array([1, 4, 7, 2, 5, 8, 3, 6, 9], dtype=int8)

In [52]:
ar3.reshape((9,1))

array([[1],
       [4],
       [7],
       [2],
       [5],
       [8],
       [3],
       [6],
       [9]], dtype=int8)

In [53]:
ar3.reshape((3,3))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [54]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int8)

In [55]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [56]:
ar2 + ar3

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]], dtype=int8)

In [57]:

ar2 * ar3

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]], dtype=int8)

In [58]:
np.sqrt(ar3)

array([[1.   , 2.   , 2.646],
       [1.414, 2.236, 2.828],
       [1.732, 2.45 , 3.   ]], dtype=float16)

In [59]:
ar3.sum()

45

In [60]:
ar3.min()

1

In [61]:
ar3.max()

9

In [62]:
ar3

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int8)

In [63]:
np.where(ar3>5)

(array([0, 1, 2, 2], dtype=int32), array([2, 2, 1, 2], dtype=int32))

In [64]:
np.count_nonzero(ar3)

9

In [65]:
import sys
py_ar=[0,2,45,48]


In [66]:
np_ar=np.array(py_ar)

In [67]:
len(py_ar) * sys.getsizeof(5)

56

In [68]:
np_ar.itemsize * np_ar.size


16

## Matrix Multiplication


In [69]:
A=np.array([[0,1,2],[2,3,4],[4,5,6]])

In [70]:
AA=np.dot(A,A)

In [71]:
AA

array([[10, 13, 16],
       [22, 31, 40],
       [34, 49, 64]])

In [72]:
5*A

array([[ 0,  5, 10],
       [10, 15, 20],
       [20, 25, 30]])

In [73]:
B=np.array([[1,0,1],[0,1,1],[1,2,0]])

In [74]:
multi_AB=np.dot(A,B)

In [75]:
multi_AB

array([[ 2,  5,  1],
       [ 6, 11,  5],
       [10, 17,  9]])

In [76]:
A==B

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## Compare Two Matrix

In [77]:
compare = A =B
print(compare.all())

False


## Determinant of Matrix

In [78]:
detA=np.linalg.det(A)

In [79]:
detA

-2.9999999999999996

In [80]:
detB=np.linalg.det(np.array([[1,1],[1,1]]))

In [81]:
detB

0.0

## Symmetric Matrix

In [82]:
# mat_A=matA.T

In [83]:
matA=np.array([[3,1,1],[1,2,2],[1,3,2]])

In [84]:
matAT=matA.T

In [85]:
matA

array([[3, 1, 1],
       [1, 2, 2],
       [1, 3, 2]])

In [86]:
matAT

array([[3, 1, 1],
       [1, 2, 3],
       [1, 2, 2]])

In [87]:
AAT=np.dot(matA,matAT)

In [88]:
AAT

array([[11,  7,  8],
       [ 7,  9, 11],
       [ 8, 11, 14]])

In [89]:
symm=matA=matAT
print(compare.all())

False


## Find 3A-2B

In [90]:
matA


array([[3, 1, 1],
       [1, 2, 3],
       [1, 2, 2]])

In [91]:
3*matA

array([[9, 3, 3],
       [3, 6, 9],
       [3, 6, 6]])

In [92]:
2 * B

array([[2, 0, 2],
       [0, 2, 2],
       [2, 4, 0]])

In [93]:
3*matA - 2*B

array([[7, 3, 1],
       [3, 4, 7],
       [1, 2, 6]])

##  An array filled with random values

In [94]:
arr11= np.random.random((3,3))

In [95]:
arr11

array([[0.77626219, 0.82692129, 0.85283572],
       [0.7366295 , 0.27666937, 0.88571281],
       [0.20922969, 0.88633855, 0.38215015]])

In [96]:
ar12=np.arange(1,10,2)

In [97]:
ar12

array([1, 3, 5, 7, 9])

## Identity Matrix


In [98]:
arr_I=np.eye(2,dtype=np.int8)
arr_I2=np.identity(3,dtype=np.int8)

In [99]:
arr_I


array([[1, 0],
       [0, 1]], dtype=int8)

In [100]:
arr_I2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

## Slicing In Array

In [101]:
arr_01=np.array([[1,2,3],[3,4,5],[4,5,6]])

In [102]:
type(arr_01)

numpy.ndarray

In [103]:
arr_01

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [104]:
arr_01[1:2]

array([[3, 4, 5]])

In [105]:
arr_01

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [106]:
arr_01[1:2,1:3]

array([[4, 5]])

## Eigen Values And Eigen Vectors

In [109]:
matrix_A= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [111]:
evalue,evector = np.linalg.eig(matrix_A)

In [115]:
print("Eingen Values : {} and\n Eigen vector : {}".format(evalue,evector))

Eingen Values : [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15] and
 Eigen vector : [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## Inverting a Matrix

In [120]:
arr_02=np.array([[1,2,3],[4,5,6],[6,7,8]])

In [122]:
invers=np.linalg.inv(arr_02)


In [123]:
invers

array([[ 5.14697100e+14, -1.28674275e+15,  7.72045650e+14],
       [-1.02939420e+15,  2.57348550e+15, -1.54409130e+15],
       [ 5.14697100e+14, -1.28674275e+15,  7.72045650e+14]])

In [114]:

arr_03=np.array([2,4,6,8])