Numpy:

<h3> How to  create numpy array ?</h3>

In [3]:
import numpy as np
arr = np.array([1,2,3,4])
strarr=np.array(["Reshma","minaxi","urvi"])
print(arr)
print(strarr)

[1 2 3 4]
['Reshma' 'minaxi' 'urvi']


In [5]:
type(arr)
type(strarr)

numpy.ndarray

In [7]:
arr.ndim

1

2d Array

In [8]:
arr_2d = np.array([[1,2,3,4],[1,2,3,4]])
print(arr_2d)
arr_2d.ndim

[[1 2 3 4]
 [1 2 3 4]]


2

In [9]:
arr_2d.size

8

In [10]:
arr_2d

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])