In [2]:
import numpy as np 

mx_one = np.ones((3,4))
print(mx_one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
mx_ones = np.ones((3,4),dtype = int)
print(mx_ones)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
mx_0s = np.zeros((4,5))
print(mx_0s)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
mx_0s = np.zeros((4,5),dtype = bool)
print(mx_0s)

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [6]:
mx_et = np.empty((3,3))
print(mx_et)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.98807563e-321]
 [1.05700345e-307 6.46572085e+170 4.44712982e+217]]
